### ISSUE TITLE
`textlint` server crashes on remote ssh from Windows to Linux machine

### ISSUE THREAD

**Issue by swarnendubiswas** [taichi/vscode-textlint#19]
I get the following error when using remote ssh from a Windows machine to a Linux machine. The `nodejs` version on the Windows machine is 14.14. 

```
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  path: '/home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 10:54:57 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  path: '/home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 10:54:58 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  path: '/home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 10:54:58 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  path: '/home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 10:54:58 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  path: '/home/swarnendu/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Error - 10:54:58 AM] Connection to server got closed. Server will not be restarted.

```

The settings on Windows are as follows.

```
   "textlint.nodePath": "C:\\Users\\swarnendu\\tmp\\textlint-workspace\\node_modules",
    "textlint.configPath": "D:\\github\\dotfiles\\textlintrc.json"
```

Do you know what is wrong here?

**Comment by swarnendubiswas** [comment]
I get a crash on with `textlint` on Windows as well. Here is the log. 

```
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\swarnendu\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 11:16:59 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\swarnendu\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 11:17:00 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\swarnendu\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 11:17:00 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\swarnendu\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 11:17:00 AM] Connection to server got closed. Server will restart.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\swarnendu\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Users\\swarnendu\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Error - 11:17:00 AM] Connection to server got closed. Server will not be restarted.
```

It seems the logs are similar.
